name: check secrets * variables

on:
  push:
    branches: env
  pull_request:
    branches: env

jobs:
  reading-variables:
    runs-on: ubuntu-latest

    steps: 
      - name: Echo variable
        run: env
